"""Tests for the HTML renderers."""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from agent_census import identity, pipeline
from agent_census.parsing import resolve
from agent_census.pipeline import RESIDENTIAL_NETWORK
from agent_census.parsing.apache import PRESETS
from agent_census.model import Classification, ClientFeatures, ClientId, ClientProfile, Kind
from agent_census.report import render_inspect_html, render_report_html, select_profiles
from agent_census.report.aggregate import KIND_CLUSTERS
from agent_census.classify.relative import _METRIC_TAGS
from agent_census.report.format import _TAG_HELP
from agent_census.report.html import _client_row, _esc

DATA = Path(__file__).parent / "data"


def _run() -> pipeline.AnalysisResult:
    parser = resolve("apache", {"format": PRESETS["combined"]})
    return pipeline.analyze(DATA / "sample_access.log", parser, identity.get_strategy("ip_ua"))


def test_every_relative_tag_has_hover_text() -> None:
    # The site-relative magnitude tags render through the same title= tooltip as
    # every other tag; a new metric must not ship without a hover description.
    missing = [tag for tag in _METRIC_TAGS.values() if tag not in _TAG_HELP]
    assert not missing, f"tags with no hover description: {missing}"


def test_report_html_is_a_full_page() -> None:
    html = render_report_html(_run(), source="sample")
    assert html.startswith("<!doctype html>")
    assert "<style>" in html
    assert html.rstrip().endswith("</html>")
    assert "Agent Census" in html
    assert "Summary by kind" in html
    # kind sections are anchored for the summary links
    assert 'id="vuln_scanner"' in html
    assert 'href="#vuln_scanner"' in html


def test_report_html_footer_links_to_pypi_with_version() -> None:
    from agent_census import __version__

    html = render_report_html(_run(), source="sample")
    assert (
        'Generated by <a href="https://pypi.org/project/agent-census">agent-census</a> '
        f"{__version__}." in html
    )


def test_report_html_shows_elapsed_note() -> None:
    html = render_report_html(_run(), source="sample", elapsed=7.25)
    assert "<em>Analysed in 7.2s</em>" in html


def test_report_html_client_cells_are_copyable() -> None:
    # The 203.0.113.66 scanner row should be click-to-copy with its id.
    html = render_report_html(_run(), source="sample")
    assert 'data-copy="203.0.113.66"' in html
    assert "navigator.clipboard" in html  # copy script present
    assert "inspect --client" in html  # the tip
    # The cell is stacked: identity line + UA line (clamped) under one copy target.
    assert '<div class="mono cid-id">203.0.113.66</div>' in html
    assert 'class="mono cid-ua"' in html


def test_kind_section_disclosure_and_filter(tmp_path: Path) -> None:
    # 8 one-off clients -> one 'unknown' kind; top 5 shown, 3 behind a disclosure.
    lines = [
        f"10.0.0.{i} - - [10/Oct/2023:12:00:0{i} +0000] " f'"GET / HTTP/1.1" 200 10 "-" "agent-{i}"'
        for i in range(8)
    ]
    log = tmp_path / "many.log"
    log.write_text("\n".join(lines) + "\n", encoding="utf-8")
    parser = resolve("apache", {"format": PRESETS["combined"]})
    result = pipeline.analyze(log, parser, identity.get_strategy("ip_ua"))
    html = render_report_html(result, source="x", top=5)

    assert '<details name="kind-extra">' in html  # shared name -> exclusive accordion
    assert "Show more" in html
    assert "scrollBy" in html  # opening one pins the clicked summary (no page jump)
    # One page-level filter sits above the sections (not inside the disclosure)…
    assert html.count('class="filter"') == 1
    assert "filter all clients" in html
    assert 'id="nomatch"' in html  # the no-match empty state the filter script fills
    # …and every detailed client row is filterable: 5 shown + 3 in the disclosure.
    assert html.count('class="frow"') == 8


def test_report_html_escapes_user_agent() -> None:
    # Inject a script payload via the UA; it must be escaped, not rendered.
    payload = "<script>alert(1)</script>"
    log = f'1.2.3.4 - - [10/Oct/2023:00:00:00 +0000] "GET / HTTP/1.1" 404 1 "-" "{payload}"'
    tmp = DATA / "_xss_tmp.log"
    tmp.write_text(log + "\n", encoding="utf-8")
    try:
        parser = resolve("apache", {"format": PRESETS["combined"]})
        result = pipeline.analyze(tmp, parser, identity.get_strategy("ip_ua"))
        html = render_report_html(result, source="x")
    finally:
        tmp.unlink()
    assert payload not in html  # the injected tag never appears raw
    assert "&lt;script&gt;alert(1)&lt;/script&gt;" in html  # it is escaped


def test_inspect_html_renders_selected() -> None:
    result = _run()
    selected = select_profiles(result, client=None, kind="vuln_scanner")
    html = render_inspect_html(selected)
    assert "Client Inspection" in html
    assert "Why this classification" in html
    assert "Request trace" in html


def test_inspect_html_empty_selection() -> None:
    html = render_inspect_html([])
    assert "No matching clients" in html


def test_inspect_html_rolls_up_ua_rotating_ip(tmp_path: Path) -> None:
    lines = [
        f'2.2.2.2 - - [10/Oct/2023:12:0{i}:00 +0000] "GET / HTTP/1.1" 200 100 "-" "rot-{i}"'
        for i in range(6)
    ]
    log = tmp_path / "rotation.log"
    log.write_text("\n".join(lines) + "\n", encoding="utf-8")
    parser = resolve("apache", {"format": PRESETS["combined"]})
    result = pipeline.analyze(log, parser, identity.get_strategy("ip_ua"))
    selected = select_profiles(result, client="2.2.2.2", kind=None)
    html = render_inspect_html(selected)
    assert "6 clients on one IP" in html
    assert "Request trace" not in html  # rolled up, not full per-client cards


def test_network_table_renders_with_providers(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(pipeline, "datacenter_subnet", lambda ip: None)
    monkeypatch.setattr(
        pipeline, "datacenter_provider", lambda ip: "Amazon AWS" if ip.startswith("52.") else None
    )
    lines = [
        '52.1.1.1 - - [10/Oct/2023:12:00:00 +0000] "GET /p HTTP/1.1" 200 100 "-" "curl/8.0"',
        '9.9.9.9 - - [10/Oct/2023:12:01:00 +0000] "GET /p HTTP/1.1" 200 100 "-" '
        '"Mozilla/5.0 (Macintosh) AppleWebKit/605.1.15 Safari/605.1.15"',
    ]
    log = tmp_path / "net.log"
    log.write_text("\n".join(lines) + "\n", encoding="utf-8")
    parser = resolve("apache", {"format": PRESETS["combined"]})
    result = pipeline.analyze(log, parser, identity.get_strategy("ip_ua"))
    html = render_report_html(result, source="x")
    assert "Requests by kind and network" in html
    assert "Amazon AWS" in html
    # The residential (non-hosting) column header carries the grey-wash + divider
    # and a hover description.
    assert f"<span>{_esc(RESIDENTIAL_NETWORK)}</span></th>" in html  # vertical header
    # first non-hosting col: divider + grey, pinned to the right edge
    assert "class='num vh netdiv stick-r netoff'" in html
    assert "Consumer ISP" in html  # residential column-header tooltip
    # Body cells carry their raw count for the JS toggle; the control + script are present.
    assert "td class='num mxcell" in html and "data-v=" in html
    assert "id='netmode'" in html and "id='nettab'" in html
    assert "rgba(220,38,38" in html  # red heat on the total row/column
    # Small-screen fold: every network column is tagged so the picker can show one
    # at a time, and tables sit in a horizontal-scroll track so none breaks the page.
    assert "id='netcol'" in html and "netcolctl" in html  # the phone column picker
    assert "data-net=" in html  # columns tagged for show/hide
    assert "class='tscroll'" in html  # tables wrapped in a scroll track
    assert "markScrollables" in html  # overflowing tracks are made keyboard-scrollable


def test_network_cells_link_client_rows_to_their_column(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    # Clicking a cross-tab number isolates that kind and filters the clients below
    # by that network. Each filterable client row is tagged with the cross-tab
    # column index/indices it belongs to (data-netcol), matched against the cells'
    # data-net by the page script.
    monkeypatch.setattr(pipeline, "datacenter_subnet", lambda ip: None)
    monkeypatch.setattr(
        pipeline, "datacenter_provider", lambda ip: "Amazon AWS" if ip.startswith("52.") else None
    )
    lines = [
        '52.1.1.1 - - [10/Oct/2023:12:00:00 +0000] "GET /p HTTP/1.1" 200 100 "-" "curl/8.0"',
        '9.9.9.9 - - [10/Oct/2023:12:01:00 +0000] "GET /p HTTP/1.1" 200 100 "-" '
        '"Mozilla/5.0 (Macintosh) AppleWebKit/605.1.15 Safari/605.1.15"',
    ]
    log = tmp_path / "net.log"
    log.write_text("\n".join(lines) + "\n", encoding="utf-8")
    parser = resolve("apache", {"format": PRESETS["combined"]})
    result = pipeline.analyze(log, parser, identity.get_strategy("ip_ua"))
    html = render_report_html(result, source="x")

    # The kind / network pills, the prominent clear control, the script hook the
    # cross-tab calls, and the click handler that drives it. Sections carry
    # data-kind so the script can isolate one kind.
    assert 'id="kindfilter"' in html and 'id="netfilter"' in html
    assert 'id="clearfilters"' in html and "Show all" in html
    assert "window.setKindNet" in html
    assert "setKindNet(kind, cell.getAttribute('data-net'))" in html
    assert "data-kind=" in html  # kind sections tagged for isolation

    # Map each column header to its index, then confirm every client row's
    # data-netcol points at a real column -- and that the two networks present
    # each tag at least one row.
    columns = {
        name: int(idx)
        for idx, name in re.findall(r"data-net='(\d+)'[^>]*><span>([^<]*)</span>", html)
    }
    assert "Amazon AWS" in columns and RESIDENTIAL_NETWORK in columns
    tagged = [set(v.split()) for v in re.findall(r'data-netcol="([^"]*)"', html)]
    assert tagged, "client rows should carry data-netcol"
    valid = {str(i) for i in columns.values()}
    assert all(cols <= valid for cols in tagged)
    assert any(str(columns["Amazon AWS"]) in cols for cols in tagged)
    assert any(str(columns[RESIDENTIAL_NETWORK]) in cols for cols in tagged)


def test_network_table_folds_datacenters_into_pinned_other(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    # Eight distinct datacenter providers (one per /8), all below the promotion
    # guard, so the busiest six show and the two smallest fold into a pinned,
    # live "Other datacenters" column. No break-out selector any more.
    monkeypatch.setattr(pipeline, "datacenter_subnet", lambda ip: None)
    monkeypatch.setattr(
        pipeline, "datacenter_provider", lambda ip: f"Provider {int(ip.split('.')[0])}"
    )
    weighted = []
    for rank, octet in enumerate(range(11, 19)):
        line = (
            f"{octet}.0.0.1 - - [10/Oct/2023:12:00:00 +0000] "
            '"GET /p HTTP/1.1" 200 100 "-" "curl/8.0"'
        )
        weighted.extend([line] * (30 - rank))
    log = tmp_path / "netmany.log"
    log.write_text("\n".join(weighted) + "\n", encoding="utf-8")
    parser = resolve("apache", {"format": PRESETS["combined"]})
    result = pipeline.analyze(log, parser, identity.get_strategy("ip_ua"))
    html = render_report_html(result, source="x")

    assert "id='netbreakout'" not in html  # the break-out selector is gone
    # The pinned, live Other column and its scaffolding.
    assert "id='netotherhd'" in html  # Other header (carries the +N cue)
    assert "othercol" in html and "othertot" in html  # Other cells tagged for the live tally
    assert "data-kind=" in html and "data-agg=" in html  # per-kind + folded-tail lookup
    assert "class='othercue'" in html  # running "+N hidden" header cue
    # Pinned and scrolling column roles.
    assert "stick-l" in html and "stick-r" in html  # Kind / Other+off-network+Total pinned
    assert " dcs'" in html or " dcs " in html  # named datacentres scroll
    # The All-kinds row's network totals carry data-v too, so the live Other *total*
    # folds in scrolled-out columns and the row keeps reconciling.
    netall = re.search(r"<tr class='netall'>.*?</tr>", html, re.S)
    assert netall is not None and netall.group(0).count("data-v=") >= 6


def test_network_table_cluster_bands(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    # The cross-tab bands its kind rows like the summary table: a pinned side label
    # per cluster plus a thick rule between bands. The band cell rides on *every*
    # row (not a rowspan) so the heat/pin script's per-column cellIndex stays uniform
    # -- the invariant this test locks. A datacenter curl client and a residential
    # browser land in two different clusters, so at least two bands render.
    monkeypatch.setattr(pipeline, "datacenter_subnet", lambda ip: None)
    monkeypatch.setattr(
        pipeline, "datacenter_provider", lambda ip: "Amazon AWS" if ip.startswith("52.") else None
    )
    lines = [
        '52.1.1.1 - - [10/Oct/2023:12:00:00 +0000] "GET /p HTTP/1.1" 200 100 "-" "curl/8.0"',
        '9.9.9.9 - - [10/Oct/2023:12:01:00 +0000] "GET /p HTTP/1.1" 200 100 "-" '
        '"Mozilla/5.0 (Macintosh) AppleWebKit/605.1.15 Safari/605.1.15"',
    ]
    log = tmp_path / "netbands.log"
    log.write_text("\n".join(lines) + "\n", encoding="utf-8")
    parser = resolve("apache", {"format": PRESETS["combined"]})
    result = pipeline.analyze(log, parser, identity.get_strategy("ip_ua"))
    html = render_report_html(result, source="x")

    table = re.search(r"<table id='nettab'>(.*?)</table>", html, re.S)
    assert table is not None
    rows = re.findall(r"<tr[^>]*>(.*?)</tr>", table.group(1), re.S)
    # Every row -- header, each kind, and the All-kinds total -- carries the same cell
    # count. A rowspan band cell would break this (and the script's column indexing).
    cell_counts = {len(re.findall(r"<t[hd][\s>]", row)) for row in rows}
    assert len(cell_counts) == 1, f"cross-tab rows are not cell-uniform: {cell_counts}"
    # Two clusters present -> two side labels and a between-band thick rule.
    labels = re.findall(r"<th class='band' scope='rowgroup'><span>([^<]+)</span>", table.group(1))
    assert len(set(labels)) >= 2
    assert set(labels) <= {c.label for c in KIND_CLUSTERS}
    assert "bandstart" in table.group(1)  # the rule that separates bands


def test_filter_haystack_includes_as_name() -> None:
    # A filterable (disclosure) row carries the shown AS name in data-filter so the
    # search box matches on it, alongside IP and User-Agent.
    profile = ClientProfile(
        client_id=ClientId(ip="52.1.1.0/24", user_agent="curl/8.0"),
        entries=(),
        features=ClientFeatures(as_org="Amazon.com, Inc."),
        classification=Classification(
            primary=Kind.SCRAPER, confidence=0.7, evidence=(), tags=frozenset({"datacenter"})
        ),
    )
    row = _client_row(profile, filterable=True)
    assert 'data-filter="' in row
    assert "amazon.com, inc." in row.lower()  # AS name folded into the haystack


def test_filter_haystack_includes_visible_tags() -> None:
    # The tags shown in the Tags column are folded into data-filter so the search
    # box matches on a tag name.
    profile = ClientProfile(
        client_id=ClientId(ip="52.1.1.0/24", user_agent="curl/8.0"),
        entries=(),
        features=ClientFeatures(as_org="Amazon.com, Inc."),
        classification=Classification(
            primary=Kind.SCRAPER,
            confidence=0.7,
            evidence=(),
            tags=frozenset({"datacenter", "scraper"}),
        ),
    )
    haystack = _client_row(profile, filterable=True)
    haystack = haystack[haystack.index('data-filter="') :].split('"', 2)[1]
    assert "datacenter" in haystack  # a visible tag is searchable
    assert "scraper" in haystack  # all shown tags are in the filter


def test_tags_have_hover_descriptions() -> None:
    # The 203.0.113.66 zgrab scanner is tagged 'probe-paths'; it should carry a tooltip.
    html = render_report_html(_run(), source="sample")
    assert '<span class="tag"' in html
    assert 'title="Requested known-vulnerable' in html


def test_esc_quotes() -> None:
    assert _esc('a"b<c>') == "a&quot;b&lt;c&gt;"


def _spark_profile(
    *, request_count: int, first, last, buckets, evidence: str = "steady cadence"
) -> ClientProfile:
    return ClientProfile(
        client_id=ClientId(ip="203.0.113.5", user_agent="Bot/1.0"),
        entries=(),
        features=ClientFeatures(
            request_count=request_count,
            first_seen=first,
            last_seen=last,
            request_buckets=tuple(buckets),
        ),
        classification=Classification(
            primary=Kind.CRAWLER, confidence=0.8, evidence=(evidence,), tags=frozenset()
        ),
    )


def test_report_html_has_request_pattern_column() -> None:
    # The cadence sparkline replaces the old free-text evidence column, and its
    # header conveys the shared time span the x-axis covers.
    html = render_report_html(_run(), source="sample")
    assert "<th class='reqpat'>Requests over " in html
    assert "Top evidence" not in html
    # The span the sparklines share is named in the header (e.g. "Requests over
    # 2h 5m") with the exact range on hover.
    assert "shared sparkline axis:" in html
    assert re.search(r"Requests over <span class='muted' title=\"[^\"]+\">[^<]+</span>", html)


def test_client_row_renders_sparkline_with_caption() -> None:
    from datetime import datetime, timedelta, timezone

    start = datetime(2023, 10, 10, 12, 0, tzinfo=timezone.utc)
    end = start + timedelta(hours=1)
    profile = _spark_profile(
        request_count=200,
        first=start,
        last=end,
        buckets=[5] * 40,
        evidence="steady, machine-paced cadence",
    )
    cell = _client_row(profile, window=(start, end))
    assert "<svg class='spark'" in cell
    assert cell.count("<rect") >= 20  # bars across the shared window
    assert "steady, machine-paced cadence" in cell  # pithy caption preserved


def test_client_row_below_threshold_is_caption_only() -> None:
    from datetime import datetime, timedelta, timezone

    start = datetime(2023, 10, 10, 12, 0, tzinfo=timezone.utc)
    end = start + timedelta(hours=1)
    profile = _spark_profile(
        request_count=12, first=start, last=end, buckets=[1] * 40, evidence="only a dozen hits"
    )
    cell = _client_row(profile, window=(start, end))
    assert "<svg" not in cell  # a handful of requests has no shape worth drawing
    assert "only a dozen hits" in cell


def test_sparkline_projects_onto_shared_axis() -> None:
    # A client active only in the first quarter of the report window lands its
    # volume in the left of the axis, leaving the rest empty -- so 'when' reads
    # comparably across rows.
    from datetime import datetime, timedelta, timezone

    from agent_census.report._sparkline import project_buckets

    start = datetime(2023, 10, 10, 12, 0, tzinfo=timezone.utc)
    window = (start, start + timedelta(hours=1))
    profile = _spark_profile(
        request_count=100, first=start, last=start + timedelta(minutes=15), buckets=[1] * 40
    )
    projected = project_buckets(profile, window)
    assert sum(projected) == 40
    assert sum(projected[:12]) == 40  # all of it in the first quarter
    assert projected[30] == 0


def test_sub_minute_client_projects_as_a_single_spike() -> None:
    # A client whose whole span fits in one minute has no span-local histogram
    # (request_buckets is empty), so it used to project to nothing and render a blank
    # glyph despite real volume. Now its whole volume lands as one spike at its point
    # in time -- consistent with how the per-kind cadence treats a sub-minute burst.
    from datetime import datetime, timedelta, timezone

    from agent_census.report._sparkline import project_buckets

    start = datetime(2023, 10, 10, 12, 0, tzinfo=timezone.utc)
    window = (start, start + timedelta(hours=4))
    active = start + timedelta(hours=1)  # a quarter of the way into the window
    profile = _spark_profile(
        request_count=200, first=active, last=active + timedelta(seconds=30), buckets=[]
    )
    assert profile.features.request_buckets == ()  # the burst that used to vanish

    projected = project_buckets(profile, window)
    assert sum(projected) == 200  # whole volume placed, not dropped
    assert sum(1 for slot in projected if slot) == 1  # ... as a single spike
    assert projected[10] == 200  # a quarter into 40 slices

    # and it now renders a glyph rather than a caption-only row
    assert "<svg class='spark'" in _client_row(profile, window=window)


def test_aggregate_buckets_reveals_rotation() -> None:
    # Two members each active in a different half: individually narrow, together
    # they cover the whole window -- the coordination signal the summary shows.
    from datetime import datetime, timedelta, timezone

    from agent_census.report._sparkline import aggregate_buckets, project_buckets

    start = datetime(2023, 10, 10, 12, 0, tzinfo=timezone.utc)
    window = (start, start + timedelta(hours=1))
    first_half = _spark_profile(
        request_count=80, first=start, last=start + timedelta(minutes=20), buckets=[1] * 40
    )
    second_half = _spark_profile(
        request_count=80,
        first=start + timedelta(minutes=40),
        last=start + timedelta(minutes=59),
        buckets=[1] * 40,
    )
    agg = aggregate_buckets([first_half, second_half], window)
    expected = sum(project_buckets(first_half, window)) + sum(project_buckets(second_half, window))
    assert sum(agg) == expected
    assert any(agg[:20]) and any(agg[20:])  # coverage on both halves


def test_summary_table_kind_sparklines_share_one_peak() -> None:
    # The 'Summary by kind' table draws a per-kind cadence glyph scaled to one peak
    # across kinds -- so a busier kind is visibly taller, conveying magnitude between
    # kinds. (The client tables share their own peak, on a per-client scale.)
    from datetime import datetime, timedelta, timezone
    from types import SimpleNamespace

    from agent_census.pipeline import _RollupAcc
    from agent_census.report._sparkline import kind_sparklines
    from agent_census.report.html import _summary_table

    start = datetime(2023, 10, 10, 12, 0, tzinfo=timezone.utc)
    window = (start, start + timedelta(hours=12))
    busy = _spark_profile(request_count=400, first=start, last=window[1], buckets=[20] * 40)
    quiet = _spark_profile(request_count=100, first=start, last=window[1], buckets=[5] * 40)

    # The summary glyph re-bins each kind's eviction-safe rollup cadence, so build the
    # rollups through the real accumulator rather than hand-rolling the histogram.
    def rollup_of(profile: ClientProfile) -> object:
        acc = _RollupAcc()
        acc.add(profile.features, respects=False, ignores=False, unknown=False)
        return acc.freeze()

    rollups = {Kind.CRAWLER: rollup_of(busy), Kind.AI_CRAWLER: rollup_of(quiet)}
    patterns = kind_sparklines(rollups, window, [Kind.CRAWLER, Kind.AI_CRAWLER])
    html = _summary_table(SimpleNamespace(rollups=rollups), patterns, window)

    assert "<th class='reqpat'>Requests over " in html  # same header as the client table
    rows = re.findall(r"<tr\b[^>]*>.*?</tr>", html)  # band-start rows carry a class
    heights = {}
    for row in rows:
        label = re.search(r'class="badge"[^>]*>([^<]+)<', row)
        svg = re.search(r"<svg class='spark'.*?</svg>", row)
        if label and svg:
            rects = [int(h) for h in re.findall(r"<rect[^>]*height='(\d+)'", svg.group(0))]
            heights[label.group(1)] = max(rects)
    # Shared peak: the busier kind is still taller. Under sqrt scaling the quarter-
    # volume kind lands at ~half height (sqrt(1/4) = 1/2), not a quarter -- so it
    # stays legible while the ordering holds.
    assert heights["crawler"] > heights["ai crawler"]
    assert heights["ai crawler"] >= heights["crawler"] // 2 - 1


def test_summary_table_bands_no_rowspan() -> None:
    # The summary table's cluster bands ride on per-row cells (label on the band's
    # first row, empty below) -- never a rowspan. A spanned cell under border-collapse
    # lets the row rules bleed across it in some browsers, which is the bug this
    # guards against; the cross-tab already proved the per-row construction renders
    # cleanly. browser + app populate a two-row People band (so a non-first, empty
    # band cell must appear); vuln_scanner opens a second band with the thick rule.
    from types import SimpleNamespace

    from agent_census.pipeline import KindRollup
    from agent_census.report.html import _summary_table

    def rollup(n: int) -> KindRollup:
        return KindRollup(clients=1, requests=n, total_bytes=n * 100, respects_robots=1)

    rollups = {Kind.BROWSER: rollup(9), Kind.APP: rollup(6), Kind.VULN_SCANNER: rollup(3)}
    html = _summary_table(SimpleNamespace(rollups=rollups), {}, None)

    assert "rowspan" not in html  # the fragile span is gone
    assert "<th class='band' scope='rowgroup'><span>People</span></th>" in html
    assert "<th class='band' scope='rowgroup'><span>Suspicious</span></th>" in html
    assert "<td class='band'></td>" in html  # app is a non-first People row
    assert "bandstart" in html  # thick rule opens the second band


def test_client_table_sparklines_share_one_peak() -> None:
    # The per-client rows share a single peak across the whole client table, so a
    # busier client's glyph is taller than a quieter one's -- height conveys volume,
    # not just shape.
    from datetime import datetime, timedelta, timezone

    from agent_census.report.html import _client_row, _client_spark_peak

    start = datetime(2023, 10, 10, 12, 0, tzinfo=timezone.utc)
    window = (start, start + timedelta(hours=1))

    def prof(ip: str, ua: str, per_slice: int, rc: int) -> ClientProfile:
        return ClientProfile(
            client_id=ClientId(ip=ip, user_agent=ua),
            entries=(),
            features=ClientFeatures(
                request_count=rc,
                first_seen=start,
                last_seen=window[1],
                request_buckets=tuple([per_slice] * 40),
            ),
            classification=Classification(
                primary=Kind.CRAWLER, confidence=0.8, evidence=("c",), tags=frozenset()
            ),
        )

    # Distinct UAs so they stay two standalone rows rather than folding into one actor.
    busy = prof("203.0.113.10", "BusyBot/1.0", 20, 800)
    quiet = prof("203.0.113.11", "QuietBot/1.0", 5, 200)  # a quarter of the per-slice volume

    def tallest(cell: str) -> int:
        return max(int(h) for h in re.findall(r"<rect[^>]*height='(\d+)'", cell))

    peak = _client_spark_peak({Kind.CRAWLER: [busy, quiet]}, window, 200)
    busy_h = tallest(_client_row(busy, window=window, peak=peak))
    quiet_h = tallest(_client_row(quiet, window=window, peak=peak))
    # Busier reads taller; sqrt keeps the quarter-volume client at ~half height, legible.
    assert busy_h > quiet_h
    assert quiet_h >= busy_h // 2 - 1
    # Without the shared peak each row scales to itself, so the quiet client would be
    # just as tall -- hiding that it does a quarter of the traffic.
    assert tallest(_client_row(quiet, window=window)) == busy_h


def test_client_spark_peak_covers_every_rendered_actor() -> None:
    # The peak has to span every actor a section renders, not just a prefix: actors
    # are ordered by total volume, but a lower-volume one (sorted later) can own the
    # spikiest single slice. Exclude it and its bar would exceed the peak and overflow
    # the glyph -- so render_report_html passes max(top, _EXPAND_LIMIT), not the bare
    # cap. (A high --top renders actors past _EXPAND_LIMIT.)
    from datetime import datetime, timedelta, timezone

    from agent_census.report._sparkline import client_spark_peak

    start = datetime(2023, 10, 10, 12, 0, tzinfo=timezone.utc)
    window = (start, start + timedelta(hours=1))

    def prof(ip: str, ua: str, buckets: list[int], rc: int) -> ClientProfile:
        return ClientProfile(
            client_id=ClientId(ip=ip, user_agent=ua),
            entries=(),
            features=ClientFeatures(
                request_count=rc,
                first_seen=start,
                last_seen=window[1],
                request_buckets=tuple(buckets),
            ),
            classification=Classification(
                primary=Kind.CRAWLER, confidence=0.8, evidence=("c",), tags=frozenset()
            ),
        )

    steady = prof("203.0.113.20", "SteadyBot/1.0", [10] * 40, 400)  # higher volume -> sorts first
    spike = [1] * 40
    spike[20] = 50  # a single tall slice, the report-wide busiest
    spiky = prof("203.0.113.21", "SpikyBot/1.0", spike, 89)  # lower volume -> sorts second

    group = {Kind.CRAWLER: [steady, spiky]}
    # A cap that omits the second (spiky) actor underestimates the peak...
    assert client_spark_peak(group, window, 1) == 10
    # ...covering both captures the spike, so no rendered bar can exceed it.
    assert client_spark_peak(group, window, 2) == 50
