"""Tests for the HTML renderers."""

from __future__ import annotations

from pathlib import Path

import pytest

from agent_census import identity, pipeline
from agent_census.parsing import resolve
from agent_census.pipeline import RESIDENTIAL_NETWORK
from agent_census.parsing.apache import PRESETS
from agent_census.model import Classification, ClientFeatures, ClientId, ClientProfile, Kind
from agent_census.report import render_inspect_html, render_report_html, select_profiles
from agent_census.classify.relative import _METRIC_TAGS
from agent_census.report.format import _TAG_HELP
from agent_census.report.html import _client_row, _esc

DATA = Path(__file__).parent / "data"


def _run() -> pipeline.AnalysisResult:
    parser = resolve("apache", {"format": PRESETS["combined"]})
    return pipeline.analyze(DATA / "sample_access.log", parser, identity.get_strategy("ip_ua"))


def test_every_relative_tag_has_hover_text() -> None:
    # The site-relative magnitude tags render through the same title= tooltip as
    # every other tag; a new metric must not ship without a hover description.
    missing = [tag for tag in _METRIC_TAGS.values() if tag not in _TAG_HELP]
    assert not missing, f"tags with no hover description: {missing}"


def test_report_html_is_a_full_page() -> None:
    html = render_report_html(_run(), source="sample")
    assert html.startswith("<!doctype html>")
    assert "<style>" in html
    assert html.rstrip().endswith("</html>")
    assert "Agent Census" in html
    assert "Summary by kind" in html
    # kind sections are anchored for the summary links
    assert 'id="vuln_scanner"' in html
    assert 'href="#vuln_scanner"' in html


def test_report_html_footer_links_to_pypi_with_version() -> None:
    from agent_census import __version__

    html = render_report_html(_run(), source="sample")
    assert (
        'Generated by <a href="https://pypi.org/project/agent-census">agent-census</a> '
        f"{__version__}." in html
    )


def test_report_html_shows_elapsed_note() -> None:
    html = render_report_html(_run(), source="sample", elapsed=7.25)
    assert "<em>Analysed in 7.2s</em>" in html


def test_report_html_client_cells_are_copyable() -> None:
    # The 203.0.113.66 scanner row should be click-to-copy with its id.
    html = render_report_html(_run(), source="sample")
    assert 'data-copy="203.0.113.66"' in html
    assert "navigator.clipboard" in html  # copy script present
    assert "inspect --client" in html  # the tip
    # The cell is stacked: identity line + UA line (clamped) under one copy target.
    assert '<div class="mono cid-id">203.0.113.66</div>' in html
    assert 'class="mono cid-ua"' in html


def test_kind_section_disclosure_and_filter(tmp_path: Path) -> None:
    # 8 one-off clients -> one 'unknown' kind; top 5 shown, 3 behind a disclosure.
    lines = [
        f"10.0.0.{i} - - [10/Oct/2023:12:00:0{i} +0000] " f'"GET / HTTP/1.1" 200 10 "-" "agent-{i}"'
        for i in range(8)
    ]
    log = tmp_path / "many.log"
    log.write_text("\n".join(lines) + "\n", encoding="utf-8")
    parser = resolve("apache", {"format": PRESETS["combined"]})
    result = pipeline.analyze(log, parser, identity.get_strategy("ip_ua"))
    html = render_report_html(result, source="x", top=5)

    assert '<details name="kind-extra">' in html  # shared name -> exclusive accordion
    assert "Show more" in html
    assert "scrollBy" in html  # opening one pins the clicked summary (no page jump)
    # One page-level filter sits above the sections (not inside the disclosure)…
    assert html.count('class="filter"') == 1
    assert "filter all clients" in html
    # …and every detailed client row is filterable: 5 shown + 3 in the disclosure.
    assert html.count('class="frow"') == 8


def test_report_html_escapes_user_agent() -> None:
    # Inject a script payload via the UA; it must be escaped, not rendered.
    payload = "<script>alert(1)</script>"
    log = f'1.2.3.4 - - [10/Oct/2023:00:00:00 +0000] "GET / HTTP/1.1" 404 1 "-" "{payload}"'
    tmp = DATA / "_xss_tmp.log"
    tmp.write_text(log + "\n", encoding="utf-8")
    try:
        parser = resolve("apache", {"format": PRESETS["combined"]})
        result = pipeline.analyze(tmp, parser, identity.get_strategy("ip_ua"))
        html = render_report_html(result, source="x")
    finally:
        tmp.unlink()
    assert payload not in html  # the injected tag never appears raw
    assert "&lt;script&gt;alert(1)&lt;/script&gt;" in html  # it is escaped


def test_inspect_html_renders_selected() -> None:
    result = _run()
    selected = select_profiles(result, client=None, kind="vuln_scanner")
    html = render_inspect_html(selected)
    assert "Client Inspection" in html
    assert "Why this classification" in html
    assert "Request trace" in html


def test_inspect_html_empty_selection() -> None:
    html = render_inspect_html([])
    assert "No matching clients" in html


def test_inspect_html_rolls_up_ua_rotating_ip(tmp_path: Path) -> None:
    lines = [
        f'2.2.2.2 - - [10/Oct/2023:12:0{i}:00 +0000] "GET / HTTP/1.1" 200 100 "-" "rot-{i}"'
        for i in range(6)
    ]
    log = tmp_path / "rotation.log"
    log.write_text("\n".join(lines) + "\n", encoding="utf-8")
    parser = resolve("apache", {"format": PRESETS["combined"]})
    result = pipeline.analyze(log, parser, identity.get_strategy("ip_ua"))
    selected = select_profiles(result, client="2.2.2.2", kind=None)
    html = render_inspect_html(selected)
    assert "6 clients on one IP" in html
    assert "Request trace" not in html  # rolled up, not full per-client cards


def test_network_table_renders_with_providers(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(pipeline, "datacenter_subnet", lambda ip: None)
    monkeypatch.setattr(
        pipeline, "datacenter_provider", lambda ip: "Amazon AWS" if ip.startswith("52.") else None
    )
    lines = [
        '52.1.1.1 - - [10/Oct/2023:12:00:00 +0000] "GET /p HTTP/1.1" 200 100 "-" "curl/8.0"',
        '9.9.9.9 - - [10/Oct/2023:12:01:00 +0000] "GET /p HTTP/1.1" 200 100 "-" '
        '"Mozilla/5.0 (Macintosh) AppleWebKit/605.1.15 Safari/605.1.15"',
    ]
    log = tmp_path / "net.log"
    log.write_text("\n".join(lines) + "\n", encoding="utf-8")
    parser = resolve("apache", {"format": PRESETS["combined"]})
    result = pipeline.analyze(log, parser, identity.get_strategy("ip_ua"))
    html = render_report_html(result, source="x")
    assert "Requests by kind and network" in html
    assert "Amazon AWS" in html
    # The residential (non-hosting) column header carries the grey-wash + divider
    # and a hover description.
    assert f">{_esc(RESIDENTIAL_NETWORK)}</th>" in html
    assert "class='num netdiv netoff'" in html  # first non-hosting col: divider + grey
    assert "Consumer ISP" in html  # residential column-header tooltip
    # Body cells carry their raw count for the JS toggle; the control + script are present.
    assert "td class='num mxcell" in html and "data-v=" in html
    assert "id='netmode'" in html and "id='nettab'" in html
    assert "rgba(220,38,38" in html  # red heat on the total row/column


def test_filter_haystack_includes_as_name() -> None:
    # A filterable (disclosure) row carries the shown AS name in data-filter so the
    # search box matches on it, alongside IP and User-Agent.
    profile = ClientProfile(
        client_id=ClientId(ip="52.1.1.0/24", user_agent="curl/8.0"),
        entries=(),
        features=ClientFeatures(as_org="Amazon.com, Inc."),
        classification=Classification(
            primary=Kind.SCRAPER, confidence=0.7, evidence=(), tags=frozenset({"datacenter"})
        ),
    )
    row = _client_row(profile, filterable=True)
    assert 'data-filter="' in row
    assert "amazon.com, inc." in row.lower()  # AS name folded into the haystack


def test_filter_haystack_includes_visible_tags() -> None:
    # The tags shown in the Tags column are folded into data-filter so the search
    # box matches on a tag name. Suppressed (section-baseline) tags are not shown,
    # so they stay out of the haystack.
    profile = ClientProfile(
        client_id=ClientId(ip="52.1.1.0/24", user_agent="curl/8.0"),
        entries=(),
        features=ClientFeatures(as_org="Amazon.com, Inc."),
        classification=Classification(
            primary=Kind.SCRAPER,
            confidence=0.7,
            evidence=(),
            tags=frozenset({"datacenter", "scraper"}),
        ),
    )
    haystack = _client_row(profile, filterable=True, suppress=frozenset({"scraper"}))
    haystack = haystack[haystack.index('data-filter="') :].split('"', 2)[1]
    assert "datacenter" in haystack  # a visible tag is searchable
    assert "scraper" not in haystack  # the suppressed tag is not shown, so not in filter


def test_tags_have_hover_descriptions() -> None:
    # The 203.0.113.66 zgrab scanner is tagged 'probe-paths'; it should carry a tooltip.
    html = render_report_html(_run(), source="sample")
    assert '<span class="tag"' in html
    assert 'title="Requested known-vulnerable' in html


def test_esc_quotes() -> None:
    assert _esc('a"b<c>') == "a&quot;b&lt;c&gt;"
